fix deposit calculation in account widget
UniqueNetwork/unique-marketplace-frontend pull request #262
Opened 2022-07-27 08:02 UTC by punkrussian72

2022-07-27 11:30 UTC, SergeyOkishev requested changes

2022-07-27 11:30 UTC, SergeyOkishev commented on src/components/Header/WalletManager/WalletManager.tsx
> +import { BN } from '@polkadot/util';
please sort imports:
1. Libs
2. "@smth"
3. aliases
4. relative paths.

2022-07-27 11:30 UTC, SergeyOkishev commented on src/components/Header/WalletManager/WalletManager.tsx
> +    if ((!sponsorshipFee?.isZero() || leader.length !== 0 || withdraw.length !== 0)) {
if ((sponsorshipFee?.isZero() || leader.length === 0 || withdraw.length === 0)) { return undefined }

less nesting - cleaner code

2022-07-28 07:02 UTC, punkrussian72 commented on src/components/Header/WalletManager/WalletManager.tsx
> +import { BN } from '@polkadot/util';
fixed

2022-07-28 07:03 UTC, punkrussian72 commented on src/components/Header/WalletManager/WalletManager.tsx
> +    if ((!sponsorshipFee?.isZero() || leader.length !== 0 || withdraw.length !== 0)) {
fixed

2022-08-01 11:54 UTC, SergeyOkishev approved these changes

2022-08-01 11:54 UTC, merged